### ISSUE TITLE
[Feature] Killaura improvement

### ISSUE THREAD

**Issue by maplepy** [RickyTheRacc/eclipse-addon#5]
Multiple suggestions I would love to see as they are in a few other clients and this addon is focused on pvp

- Add a FOV to not 180 on people so it looks _legit_
- Add a custom range, depending on the weapon used like coffee client does for instance so it doesnt proc anti cheats
- Whether to target friends or not
- Whether to target teammates or not

**Comment by RickyTheRacc** [comment]
If I could ban you from opening issues I would, stop cheating on servers that don't allow it freak

**Comment by maplepy** [comment]
> Based PVP addon for Meteor Client. 

not so based after all
